### ISSUE TITLE
ambiguous title of the project

### ISSUE THREAD

**Issue by jowagner** [pingpong-ai/xlnet-pytorch#4]
The title "2019 Google Brain's XLNet Pytorch Implementation" can be misunderstood that this a google brain repository offering an implementation of XLNet in PyTorch.

Suggestion: "An implementation of Google Brain's 2019 XLNet in PyTorch"

**Comment by codertimo** [comment]
Oh that's a good point :) Thank you let us know about it!
Sorry English is not my main language, so there could be some weird point on my repo haha.
I fixed the description as you suggested!
